# Generated by Django 5.2.13 on 2026-05-02 17:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=32, verbose_name='Šaltinis')),
                ('source_url', models.URLField(max_length=500, verbose_name='Šaltinio nuoroda')),
                ('source_id', models.CharField(max_length=64, verbose_name='Šaltinio ID')),
                ('content_hash', models.CharField(db_index=True, max_length=64, verbose_name='Turinio hash')),
                ('title', models.CharField(max_length=500, verbose_name='Pavadinimas')),
                ('description', models.TextField(blank=True, verbose_name='Aprašymas')),
                ('property_type', models.CharField(choices=[('house', 'Namas'), ('flat', 'Butas'), ('plot', 'Sklypas'), ('commercial', 'Komercinis'), ('cottage', 'Sodyba'), ('part_of_house', 'Namo dalis')], db_index=True, max_length=16, verbose_name='Turto tipas')),
                ('listing_type', models.CharField(choices=[('sale', 'Pardavimas'), ('rent', 'Nuoma')], db_index=True, max_length=8, verbose_name='Skelbimo tipas')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Kaina')),
                ('price_per_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kaina už kv.m')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Valiuta')),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Plotas kv.m')),
                ('plot_area_ares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sklypo plotas arais')),
                ('rooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Kambariai')),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Aukštas')),
                ('total_floors', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Aukštų skaičius')),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Statybos metai')),
                ('building_type', models.CharField(blank=True, choices=[('brick', 'Mūrinis'), ('block', 'Blokinis'), ('wooden', 'Medinis'), ('monolithic', 'Monolitinis'), ('log', 'Rąstinis'), ('frame', 'Karkasinis'), ('other', 'Kita')], max_length=16, verbose_name='Pastato tipas')),
                ('heating_type', models.CharField(blank=True, max_length=64, verbose_name='Šildymas')),
                ('energy_class', models.CharField(blank=True, max_length=8, verbose_name='Energijos klasė')),
                ('is_new_construction', models.BooleanField(db_index=True, default=False, verbose_name='Naujos statybos')),
                ('address_raw', models.CharField(max_length=500, verbose_name='Adresas (originalus)')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Miestas')),
                ('municipality', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Savivaldybė')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Rajonas / mikrorajonas')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='Koordinatės')),
                ('cadastral_number', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Kadastro numeris')),
                ('photo_urls', models.JSONField(default=list, verbose_name='Nuotraukų nuorodos')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='Pirmas pastebėjimas')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Paskutinis pastebėjimas')),
                ('scraped_at', models.DateTimeField(verbose_name='Nuskaityta')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktyvus')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Neapdoroti duomenys')),
            ],
            options={
                'verbose_name': 'Skelbimas',
                'verbose_name_plural': 'Skelbimai',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['property_type', 'listing_type', 'is_active'], name='listings_li_propert_a20375_idx'), models.Index(fields=['price'], name='listings_li_price_d6caaa_idx'), models.Index(fields=['area_sqm'], name='listings_li_area_sq_b1aa97_idx'), models.Index(fields=['rooms'], name='listings_li_rooms_4641e1_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_id'), name='unique_source_listing')],
            },
        ),
    ]
