# Generated by Django 5.2.13 on 2026-05-03 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='Priežastis')),
                ('excluded_at', models.DateTimeField(auto_now_add=True, verbose_name='Pašalinta')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exclusion', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Pašalintas skelbimas',
                'verbose_name_plural': 'Pašalinti skelbimai',
            },
        ),
    ]
