# Generated by Django 5.2.13 on 2026-05-02 19:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=16, unique=True, verbose_name='Įmonės kodas')),
                ('name', models.CharField(max_length=300, verbose_name='Pavadinimas')),
                ('nace_codes', models.JSONField(default=list, verbose_name='EVRK kodai')),
                ('registered_address', models.CharField(max_length=500, verbose_name='Registruotas adresas')),
                ('registered_address_point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Adreso koordinatės')),
                ('founded', models.DateField(blank=True, null=True, verbose_name='Įsteigta')),
                ('status', models.CharField(max_length=32, verbose_name='Statusas')),
                ('employee_count', models.IntegerField(blank=True, null=True, verbose_name='Darbuotojų skaičius')),
                ('last_synced_at', models.DateTimeField(auto_now=True, verbose_name='Paskutinis sinchronizavimas')),
            ],
            options={
                'verbose_name': 'Vystytojas',
                'verbose_name_plural': 'Vystytojai',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status'], name='developers__status_0e3aa3_idx'), models.Index(fields=['name'], name='developers__name_8762ba_idx')],
            },
        ),
    ]
