# Generated by Django 5.2.13 on 2026-05-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Šaltinio URL')),
                ('storage_path', models.CharField(blank=True, max_length=500, verbose_name='Saugojimo kelias')),
                ('title', models.CharField(max_length=500, verbose_name='Pavadinimas')),
                ('extracted_text', models.TextField(blank=True, verbose_name='Ištrauktas tekstas')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='Failo dydis (baitais)')),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Turinio maišos kodas')),
                ('extracted_at', models.DateTimeField(blank=True, null=True, verbose_name='Tekstas ištrauktas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
            ],
            options={
                'verbose_name': 'Dokumentas',
                'verbose_name_plural': 'Dokumentai',
                'ordering': ['-created_at'],
            },
        ),
    ]
