# Generated by Django 5.2.13 on 2026-05-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Pavadinimas')),
                ('lat', models.FloatField(verbose_name='Platuma')),
                ('lng', models.FloatField(verbose_name='Ilguma')),
                ('radius_m', models.IntegerField(default=5000, verbose_name='Spindulys (m)')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Min kaina')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Max kaina')),
                ('rooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Kambariai')),
                ('property_type', models.CharField(blank=True, max_length=16, verbose_name='Turto tipas')),
                ('listing_type', models.CharField(default='sale', max_length=8, verbose_name='Skelbimo tipas')),
                ('is_new_construction', models.BooleanField(null=True, verbose_name='Naujos statybos')),
                ('last_notified_at', models.DateTimeField(auto_now_add=True, verbose_name='Pask. pranešimas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktyvus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
            ],
            options={
                'verbose_name': 'Išsaugotas paieška',
                'verbose_name_plural': 'Išsaugotos paieškos',
                'ordering': ['-created_at'],
            },
        ),
    ]
