# Generated by Django 5.2.13 on 2026-05-02 19:27

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastralPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastral_number', models.CharField(max_length=64, unique=True, verbose_name='Kadastro numeris')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326, verbose_name='Geometrija')),
                ('area_sqm', models.FloatField(verbose_name='Plotas kv.m')),
                ('purpose', models.CharField(blank=True, max_length=200, verbose_name='Paskirtis')),
                ('purpose_category', models.CharField(blank=True, max_length=64, verbose_name='Paskirties kategorija')),
                ('municipality', models.CharField(blank=True, max_length=100, verbose_name='Savivaldybė')),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sinchronizuota')),
            ],
            options={
                'verbose_name': 'Kadastro sklypas',
                'verbose_name_plural': 'Kadastro sklypai',
                'ordering': ['-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='HeritageObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kvr_code', models.CharField(max_length=64, unique=True, verbose_name='KVR kodas')),
                ('name', models.CharField(max_length=500, verbose_name='Pavadinimas')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Kategorija')),
                ('protection_level', models.CharField(blank=True, max_length=64, verbose_name='Apsaugos lygis')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(geography=True, srid=4326, verbose_name='Geometrija')),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sinchronizuota')),
            ],
            options={
                'verbose_name': 'Kultūros paveldo objektas',
                'verbose_name_plural': 'Kultūros paveldo objektai',
                'ordering': ['-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialLandUseCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, verbose_name='Kategorija')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326, verbose_name='Geometrija')),
                ('description', models.TextField(blank=True, verbose_name='Aprašymas')),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sinchronizuota')),
            ],
            options={
                'verbose_name': 'Specialioji žemės naudojimo sąlyga',
                'verbose_name_plural': 'Specialiosios žemės naudojimo sąlygos',
                'ordering': ['-synced_at'],
            },
        ),
    ]
