# Generated by Django 5.2.13 on 2026-05-02 19:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastre', '0001_initial'),
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(max_length=64, unique=True, verbose_name='Leidimo numeris')),
                ('permit_type', models.CharField(blank=True, max_length=64, verbose_name='Leidimo tipas')),
                ('status', models.CharField(blank=True, max_length=32, verbose_name='Statusas')),
                ('issued_at', models.DateField(blank=True, null=True, verbose_name='Išdavimo data')),
                ('applicant_name', models.CharField(blank=True, max_length=500, verbose_name='Statytojas / užsakovas')),
                ('cadastral_number', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Kadastro numeris')),
                ('address_raw', models.CharField(blank=True, max_length=500, verbose_name='Adresas')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Koordinatės')),
                ('project_description', models.TextField(blank=True, verbose_name='Projekto aprašymas')),
                ('project_type', models.CharField(blank=True, max_length=64, verbose_name='Projekto tipas')),
                ('building_purpose', models.CharField(blank=True, max_length=64, verbose_name='Pastato paskirtis')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Neapdoroti duomenys')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='Šaltinio nuoroda')),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Nuskaitymo laikas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinta')),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permits_as_applicant', to='developers.developer', verbose_name='Vystytojas (statytojas)')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permits_as_contractor', to='developers.developer', verbose_name='Rangovas')),
                ('plot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permits', to='cadastre.cadastralplot', verbose_name='Kadastro sklypas')),
            ],
            options={
                'verbose_name': 'Statybos leidimas',
                'verbose_name_plural': 'Statybos leidimai',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['status'], name='permits_bui_status_f07bf9_idx'), models.Index(fields=['permit_type'], name='permits_bui_permit__d0bc17_idx'), models.Index(fields=['issued_at'], name='permits_bui_issued__8a57c4_idx')],
            },
        ),
    ]
