# Generated by Django 5.2.13 on 2026-05-02 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('match', 'Tinka'), ('review', 'Peržiūrėti'), ('skip', 'Praleisti')], db_index=True, max_length=8, verbose_name='Verdiktas')),
                ('match_score', models.FloatField(verbose_name='Atitikimo balas')),
                ('summary', models.TextField(verbose_name='AI santrauka')),
                ('hard_filter_results', models.JSONField(default=dict, verbose_name='Filtrų rezultatai')),
                ('quality_notes', models.JSONField(default=list, verbose_name='Kokybės pastabos')),
                ('red_flags', models.JSONField(default=list, verbose_name='Raudonos vėliavos')),
                ('classified_at', models.DateTimeField(auto_now_add=True, verbose_name='Klasifikuota')),
                ('model_used', models.CharField(max_length=64, verbose_name='Naudotas modelis')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Skelbimo vertinimas',
                'verbose_name_plural': 'Skelbimų vertinimai',
                'ordering': ['-match_score'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('like', 'Patinka'), ('dislike', 'Nepatinka')], max_length=8, verbose_name='Tipas')),
                ('reason', models.TextField(verbose_name='Priežastis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Vartotojo atsiliepimas',
                'verbose_name_plural': 'Vartotojo atsiliepimai',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearnedPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_type', models.CharField(choices=[('like', 'Prioritizuoti'), ('dislike', 'Vengti')], max_length=8, verbose_name='Tipas')),
                ('pattern', models.TextField(verbose_name='Šablonas')),
                ('weight', models.FloatField(default=1.0, verbose_name='Svoris')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktyvus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('source_feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_preferences', to='classifier.userfeedback', verbose_name='Šaltinio atsiliepimas')),
            ],
            options={
                'verbose_name': 'Išmoktas prioritetas',
                'verbose_name_plural': 'Išmokti prioritetai',
                'ordering': ['-created_at'],
            },
        ),
    ]
