# Generated by Django 5.2.13 on 2026-05-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingevaluation',
            name='classified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Klasifikuota'),
        ),
    ]
