# Generated by Django 5.2.13 on 2026-05-02 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_change_classified_at_to_auto_now'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(verbose_name='AI pasitikėjimas')),
                ('reasoning', models.TextField(verbose_name='AI paaiškinimas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinta')),
                ('canonical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_for', to='listings.listing', verbose_name='Pagrindinis skelbimas')),
                ('listings', models.ManyToManyField(related_name='clusters', to='listings.listing', verbose_name='Skelbimai klasteryje')),
            ],
            options={
                'verbose_name': 'Skelbimų klasteris',
                'verbose_name_plural': 'Skelbimų klasteriai',
                'ordering': ['-updated_at'],
            },
        ),
    ]
