# Generated by Django 5.2.13 on 2026-05-02 19:36

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpdris_id', models.CharField(max_length=64, unique=True, verbose_name='TPDRIS identifikatorius')),
                ('title', models.CharField(max_length=500, verbose_name='Pavadinimas')),
                ('doc_type', models.CharField(choices=[('master', 'Bendrasis planas'), ('detailed', 'Detalusis planas'), ('special', 'Specialusis planas')], max_length=16, verbose_name='Dokumento tipas')),
                ('status', models.CharField(choices=[('preparation', 'Rengiamas'), ('public_review', 'Viešas svarstymas'), ('approved', 'Patvirtintas'), ('rejected', 'Atmestas'), ('expired', 'Nebegalioja')], max_length=16, verbose_name='Būsena')),
                ('municipality', models.CharField(max_length=100, verbose_name='Savivaldybė')),
                ('organizer', models.CharField(blank=True, max_length=300, verbose_name='Organizatorius')),
                ('approved_at', models.DateField(blank=True, null=True, verbose_name='Patvirtinimo data')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Galiojimo pabaiga')),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='Ribos')),
                ('allowed_uses', models.JSONField(default=list, verbose_name='Leistinos paskirtys')),
                ('max_height_m', models.FloatField(blank=True, null=True, verbose_name='Maks. aukštis (m)')),
                ('max_floors', models.IntegerField(blank=True, null=True, verbose_name='Maks. aukštų skaičius')),
                ('max_density', models.FloatField(blank=True, null=True, verbose_name='Maks. užstatymo tankis')),
                ('parking_requirements', models.TextField(blank=True, verbose_name='Automobilių stovėjimo reikalavimai')),
                ('extraction_confidence', models.FloatField(blank=True, null=True, verbose_name='Ištraukimo patikimumas')),
                ('source_url', models.URLField(verbose_name='Šaltinio URL')),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Nuskanuota')),
                ('documents', models.ManyToManyField(blank=True, to='documents.document', verbose_name='Dokumentai')),
            ],
            options={
                'verbose_name': 'Teritorijų planavimo dokumentas',
                'verbose_name_plural': 'Teritorijų planavimo dokumentai',
                'ordering': ['-approved_at', '-scraped_at'],
                'indexes': [models.Index(fields=['doc_type'], name='planning_pl_doc_typ_74a7f5_idx'), models.Index(fields=['status'], name='planning_pl_status_f64646_idx'), models.Index(fields=['municipality'], name='planning_pl_municip_1beb89_idx')],
            },
        ),
    ]
